name: Build

on:
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Verify README generation
        uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v1
        with:
          project_status: official
          project_stability: experimental
          project_type: other

      - name: Shared Build Steps
        uses: momentohq/standards-and-practices/github-actions/shared-build@gh-actions-v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build Packages
        run: ./build-all-npm-packages.sh